spring:
  profiles.active: local
---
server:
  port: 9091
spring:
  profiles: local
  aop:
    auto: true
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/db_test
    username: admin
    password: admin
    driver-class-name: com.mysql.jdbc.Driver
    initial-size: 5
    max-active: 20
    min-idle: 2
    validation-query: SELECT 1
    test-on-borrow: true
    test-while-idle: true

mybatis:
  config-location: classpath:mybatis-config.xml
